# LINEAR ALGEBRA (Vector & Matrix)

# 1) Vectors
    --  A Vector is an ordered list of numbers

In [1]:
import numpy as np

# Create a Vector
student=np.array([85,90,60,75])

print("Vector: ", student)
print("Shape: ", student.shape)
print("Data Ttype: ", student.dtype)

Vector:  [85 90 60 75]
Shape:  (4,)
Data Ttype:  int64


# Vector Operation
  - Add , Scales and compares vectors all the time

1. Add

In [ ]:
v1=np.array([1,2,3])
v2=np.array([5,6,7])
print("Addition: ", v1+v2)

Addition:  [ 6  8 10]
Multiplication:  [ 5.  6. 15.]
56


2. Multiplication

In [ ]:
weight=np.array([0.5,1.5,2.5])
feature=np.array([10,4,6])

result = weight * feature
print("Multiplication: ", result) 

3. Dot Product

In [ ]:
x=np.array([2,3,4])
y=np.array([5,6,7])

dot=np.dot(x,y)
print(dot)

# 2) Matrices
    -- A Matrix is a table of numbers(rows & columns)
    in Excel Sheet:
        Rows --> Data points
        Columns --> Features

In [ ]:
import numpy as np

# dataset: 3 students, 3 features
data = np.array([
    [85, 90, 6],
    [78, 88, 5],
    [92, 95, 8]
]) 
print("MAtrix:\n", data)
print("Shape: ", data.shape)

print("First student: ", data[0])
print("Marks column: ", data[0])

MAtrix:
 [[85 90  6]
 [78 88  5]
 [92 95  8]]
Shape:  (3, 3)


# Matrix Operations

4. Multiplication (dot product)

In [ ]:

x=np.array([
    [1,2],
    [3,4],
    [5,6]
])
w=np.array([
    [0.5],
    [1.0]
])
prediction = np.dot(x,w)
print(prediction)

[[2.5]
 [5.5]
 [8.5]]
Transpose:
 [[1 3 5]
 [2 4 6]]
Identifier:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
def matrix_multiplication(mat1,mat2):
    # get the no of rows and colums for both matrixes
    row_mat1=len(mat1)
    cols_mat1=len(mat1[0])
    row_mat2=len(mat2)
    cols_mat2=len(mat2[0])

    # Chek if multiplication is passible
    if cols_mat1 != row_mat2:
        raise ValueError("Number of columns in mat1 must be equal to munber of rows in mat2")
    # Initialize the result mat with zero to store values
    result =  [[0 for _ in range(cols_mat2)] for _ in range(row_mat1)]

    # Perform mat multiplication using method for loop
    for i in range(row_mat1):
        for j in range(cols_mat2):
            for k in range(cols_mat1):
                result[i][j] += mat1[i][k] * mat2[k][j]
    return result

# Example usage:
mat1 = [
    [1,2,3],
    [4,5,6]
]
mat2 = [
    [7,8],
    [9,10],
    [11,12]
]

result = matrix_multiplication(mat1,mat2)

# printing the result
print("Resultant Matrix:")
for row in result:
    print(row)

Resultant Matrix:
[58, 64]
[139, 154]


5. Create a random matrix and dot matrix

In [ ]:
L = np.random.rand(3,2)
M = np.random.rand(2,4)
P = np.dot(L,M)
print("Matrix L:\n",L)
print("Matrix M:\n",M)
print("Matrix P:\n", P)

Matrix L:
 [[0.92561461 0.06667986]
 [0.52962528 0.29580461]
 [0.22728465 0.2819677 ]]
Matrix M:
 [[0.74830018 0.40836824 0.35692645 0.1726479 ]
 [0.6738955  0.40656679 0.10450404 0.57728367]]
Matrix P:
 [[0.73757283 0.40510142 0.33734465 0.19829861]
 [0.59566009 0.33654648 0.21995005 0.26220186]
 [0.36009391 0.20745453 0.11059067 0.20201557]]


6. Transpose matrix

In [ ]:
transpose_x=x.T
print("Matrix x:\n", x)
print("Transpose Matrix:\n",x.T)

Matrix x:
 [[1 2]
 [3 4]
 [5 6]]
Transpose Matrix:
 [[1 3 5]
 [2 4 6]]


7. Identify Matrix

In [ ]:
P = np.eye(2)
print(P)
I = np.eye(3)
print("Identifier: ",I)

[[1. 0.]
 [0. 1.]]
Identifier:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8.  Determinations


In [ ]:
A = np.array([
            [1,2],
            [3,4]])
det_A = np.linalg.det(A)
print("Determinat of A: ", det_A)

Determinat of A:  -2.0000000000000004


9. Inverse of a matrix

In [22]:
try:
    inv_A = np.linalg.inv(A)
    print("Invetse of A:\n", inv_A)
except np.linalg.LinAlgError:
    # Singular matrix is a matrix with det() = 0
    print("Matrix A is singulat and not have an inverse.")

Invetse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


10. Eigenvalues and Eigenvectors

In [26]:
eigenvalues , eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:\n",eigenvalues)
print("Eigenvectors of A:\n",eigenvectors)


Eigenvalues of A:
 [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


11. Solving a System of linear equation (Ax=b)

In [27]:
b = np.array([5,7])

#Solve the System
solution = np.linalg.solve(A,b)
print("MAtrix A:\n ", A)
print("Vector b:\n ", b)
print(f"Solutiion of the System Ax = b where b = {b}:\n",solution)

MAtrix A:
  [[1 2]
 [3 4]]
Vector b:
  [5 7]
Solutiion of the System Ax = b where b = [5 7]:
 [-3.  4.]
