# LINEAR ALGEBRA (Vector & Matrix)

# 1) Vectors
    --  A Vector is an ordered list of numbers

In [9]:
import numpy as np

# Create a Vector
student=np.array([85,90,60,75])

print("Vector: ", student)
print("Shape: ", student.shape)
print("Data Ttype: ", student.dtype)

Vector:  [85 90 60 75]
Shape:  (4,)
Data Ttype:  int64


# Vector Operation
  - Add , Scales and compares vectors all the time

1. Add

In [10]:
v1=np.array([1,2,3])
v2=np.array([5,6,7])
print("Addition: ", v1+v2)

Addition:  [ 6  8 10]


2. Multiplication

In [11]:
weight=np.array([0.5,1.5,2.5])
feature=np.array([10,4,6])

result = weight * feature
print("Multiplication: ", result) 

Multiplication:  [ 5.  6. 15.]


3. Dot Product

In [12]:
x=np.array([2,3,4])
y=np.array([5,6,7])

dot=np.dot(x,y)
print("The dot product of b.a is the same as a.b: ",dot)

# There are three different ways to represent the dot product of two vectors.

# a**T*b
# a.b
# < a, b >

The dot product of b.a is the same as a.b:  56


In [13]:
# Magnitude of a Vector
# To calculate the magnitude of vector a, we just need to use numpy as such: 

# Magnitude = np.norm(a)

we also can a operations of:
1. Vector Division: (a / b)
2. Vector Scalar Multiplication: (a*n) #n=2


# Vector Projection:
 A vector projection of vector a onto another vector b is the orthogonal projection of a onto b.

In [14]:
import numpy as np1
from numpy import linalg as lng

In [15]:

a = np1.array([20, 30, 40, 50]) # Vector a
b = np1.array([60, 70, 80, 90]) # Vector b

In [16]:
# To calculate a norm of the vector a:
lng.norm(a)

np.float64(73.48469228349535)

In [17]:
# The projection of a vector a onto vector b is the division of the dot product of (a,b) and the dot product of (b,b) multiplied by the vector b:

vector_projection = (np1.dot(a, b) / np1.dot(b, b)) * b
print(vector_projection)

[28.69565217 33.47826087 38.26086957 43.04347826]


In [18]:
# Changing Basis of Vectors

In [19]:
# Basis Vectors have three properties:
# 1: Are linearly independent of each other
# 2: Span the whole space
# 3: Aren't unique

In [20]:
a = [4, -3]
a = 1 * [2, 1] + (-2) * [-1, 2]
print(a)

[2, 1]


In [21]:
# Example of matrix-vector multiplication using the symbol @

A = np.array([[2, 1],
              [1, 3]])

B = np.array([4, 5])

result = A @ B  # Matrix-vector multiplication

print(result)

[13 19]


In [25]:
# Original basis vectors
basis_original = np1.array([[2, 1],
                           [1, 3]])

# New basis vectors
basis_new = np1.array([[3, -1],
                      [1, 2]])

# Vector in the original basis
vector_original = np1.array([4, 5])

# Compute the transformation matrix from original to new basis
transformation_matrix = np1.linalg.inv(basis_original) @ basis_new

# Transform the vector to the new basis
vector_new = transformation_matrix @ vector_original

print("Original Vector:", vector_original)
print("Vector in New Basis:", vector_new)

Original Vector: [4 5]
Vector in New Basis: [1.4 4.2]


In [23]:
# Basis, Linear Independence, and Span

In [24]:
# Spanning Set:
# The set {v1, ..., vn} is a spanning set for V if and only if every vector in V can be written as a linear combination of v1, ..., vn.

In [ ]:
# Original basis vectors
basis = np1.array([[2, 1],
                  [1, 3]])

# Vectors for demonstrating span
vector1 = np1.array([2, 1])
vector2 = np1.array([-1, 2])
vector3 = np1.array([3, 5])

# Check linear independence
vectors = np1.vstack((vector1, vector2, vector3))
linear_independent = np1.linalg.matrix_rank(vectors) == vectors.shape[0]

# Check if vectors span the space
spanning_matrix = np1.vstack((vector1, vector2, vector3))
spanning_space = np1.linalg.matrix_rank(spanning_matrix) == basis.shape[0]

print("Original Basis:")
print(basis)

print("\nVectors for Demonstrating Span:")
print(vector1)
print(vector2)
print(vector3)

print("\nLinear Independence:", linear_independent)
print("Spanning the Space:", spanning_space)

# 2) Matrices
    -- A Matrix is a table of numbers(rows & columns)
    in Excel Sheet:
        Rows --> Data points
        Columns --> Features

In [7]:
import numpy as np

# dataset: 3 students, 3 features
data = np.array([
    [85, 90, 6],
    [78, 88, 5],
    [92, 95, 8]
]) 
print("MAtrix:\n", data)
print("Shape: ", data.shape)

print("First student: ", data[0])
print("Marks column: ", data[0])

MAtrix:
 [[85 90  6]
 [78 88  5]
 [92 95  8]]
Shape:  (3, 3)
First student:  [85 90  6]
Marks column:  [85 90  6]


# Matrix Operations

4. Multiplication (dot product)

In [ ]:

x=np.array([
    [1,2],
    [3,4],
    [5,6]
])
w=np.array([
    [0.5],
    [1.0]
])
prediction = np.dot(x,w)
print(prediction)

[[2.5]
 [5.5]
 [8.5]]
Transpose:
 [[1 3 5]
 [2 4 6]]
Identifier:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
def matrix_multiplication(mat1,mat2):
    # get the no of rows and colums for both matrixes
    row_mat1=len(mat1)
    cols_mat1=len(mat1[0])
    row_mat2=len(mat2)
    cols_mat2=len(mat2[0])

    # Chek if multiplication is passible
    if cols_mat1 != row_mat2:
        raise ValueError("Number of columns in mat1 must be equal to munber of rows in mat2")
    # Initialize the result mat with zero to store values
    result =  [[0 for _ in range(cols_mat2)] for _ in range(row_mat1)]

    # Perform mat multiplication using method for loop
    for i in range(row_mat1):
        for j in range(cols_mat2):
            for k in range(cols_mat1):
                result[i][j] += mat1[i][k] * mat2[k][j]
    return result

# Example usage:
mat1 = [
    [1,2,3],
    [4,5,6]
]
mat2 = [
    [7,8],
    [9,10],
    [11,12]
]

result = matrix_multiplication(mat1,mat2)

# printing the result
print("Resultant Matrix:")
for row in result:
    print(row)

Resultant Matrix:
[58, 64]
[139, 154]


5. Create a random matrix and dot matrix

In [ ]:
L = np.random.rand(3,2)
M = np.random.rand(2,4)
P = np.dot(L,M)
print("Matrix L:\n",L)
print("Matrix M:\n",M)
print("Matrix P:\n", P)

Matrix L:
 [[0.92561461 0.06667986]
 [0.52962528 0.29580461]
 [0.22728465 0.2819677 ]]
Matrix M:
 [[0.74830018 0.40836824 0.35692645 0.1726479 ]
 [0.6738955  0.40656679 0.10450404 0.57728367]]
Matrix P:
 [[0.73757283 0.40510142 0.33734465 0.19829861]
 [0.59566009 0.33654648 0.21995005 0.26220186]
 [0.36009391 0.20745453 0.11059067 0.20201557]]


6. Transpose matrix

In [ ]:
transpose_x=x.T
print("Matrix x:\n", x)
print("Transpose Matrix:\n",x.T)

Matrix x:
 [[1 2]
 [3 4]
 [5 6]]
Transpose Matrix:
 [[1 3 5]
 [2 4 6]]


7. Identify Matrix

In [ ]:
P = np.eye(2)
print(P)
I = np.eye(3)
print("Identifier: ",I)

[[1. 0.]
 [0. 1.]]
Identifier:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8.  Determinations


In [ ]:
A = np.array([
            [1,2],
            [3,4]])
det_A = np.linalg.det(A)
print("Determinat of A: ", det_A)

Determinat of A:  -2.0000000000000004


9. Inverse of a matrix

In [22]:
try:
    inv_A = np.linalg.inv(A)
    print("Invetse of A:\n", inv_A)
except np.linalg.LinAlgError:
    # Singular matrix is a matrix with det() = 0
    print("Matrix A is singulat and not have an inverse.")

Invetse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


10. Eigenvalues and Eigenvectors

In [26]:
eigenvalues , eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:\n",eigenvalues)
print("Eigenvectors of A:\n",eigenvectors)


Eigenvalues of A:
 [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


11. Solving a System of linear equation (Ax=b)

In [27]:
b = np.array([5,7])

#Solve the System
solution = np.linalg.solve(A,b)
print("MAtrix A:\n ", A)
print("Vector b:\n ", b)
print(f"Solutiion of the System Ax = b where b = {b}:\n",solution)

MAtrix A:
  [[1 2]
 [3 4]]
Vector b:
  [5 7]
Solutiion of the System Ax = b where b = [5 7]:
 [-3.  4.]
